#ifndef POWER_CONTROLLER_EVERY2_INDEXPAGE_H
#define POWER_CONTROLLER_EVERY2_INDEXPAGE_H

char* page[] = {
        F(R"===(<!DOCTYPE html>)==="),
        F(R"===(<html lang="en">)==="),
        F(R"===(<head>)==="),
        F(R"===(<meta charset="UTF-8">)==="),
        F(R"===(<meta charset="utf-8">)==="),
        F(R"===(<meta name="viewport" content="width=device-width, initial-scale=1">)==="),
        F(R"===(<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">)==="),
        F(R"===(<script   src="https://code.jquery.com/jquery-3.5.1.min.js"   integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="   crossorigin="anonymous"></script>)==="),
        F(R"===(<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>)==="),
        F(R"===(<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js" integrity="sha512-vBmx0N/uQOXznm/Nbkp7h0P1RfLSj0HQrFSzV8m7rOGyj30fYAOKHYvCNez+yM8IrfnW0TCodDEjRqf6fodf/Q==" crossorigin="anonymous"></script>)==="),
        F(R"===(<title>Power Controller</title>)==="),
        F(R"===(</head>)==="),
        F(R"===(<body>)==="),
        F(R"===(<div class="container">)==="),
        F(R"===(<div class="row">)==="),
        F(R"===(<div class="col-6">)==="),
        F(R"===(<h4 class="text-center">Power</h4>)==="),
        F(R"===(<div class="col-11">)==="),
        F(R"===(<div class="row">)==="),
        F(R"===(<table class="table table-sm table-borderless">)==="),
        F(R"===(<thead>)==="),
        F(R"===(<tr>)==="),
        F(R"===(<th scope="col"></th>)==="),
        F(R"===(<th scope="col">Status</th>)==="),
        F(R"===(<th colspan="2" scope="col">Actions</th>)==="),
        F(R"===(</tr>)==="),
        F(R"===(</thead>)==="),
        F(R"===(<tbody>)==="),
        F(R"===(<tr>)==="),
        F(R"===(<td class="align-middle" id="n0"></td>)==="),
        F(R"===(<td class="align-middle"><div id="s0"></div></td>)==="),
        F(R"===(<td class="align-middle"><form method="post"><input name="power0" type="hidden" value="1" id="i0"><button type="submit" id="b0"></button></form></td>)==="),
        F(R"===(<td class="align-middle"><form method="post"><input name="power0" type="hidden" value="2"><button type="submit" class="btn btn-dark btn-block">Cycle</button></form></td>)==="),
        F(R"===(</tr>)==="),
        F(R"===(<tr>)==="),
        F(R"===(<td class="align-middle" id="n1"></td>)==="),
        F(R"===(<td class="align-middle"><div id="s1"></div></td>)==="),
        F(R"===(<td class="align-middle"><form method="post"><input name="power1" type="hidden" value="1" id="i1"><button type="submit" id="b1"></button></form></td>)==="),
        F(R"===(<td class="align-middle"><form method="post"><input name="power1" type="hidden" value="2"><button type="submit" class="btn btn-block btn-dark">Cycle</button></form></td>)==="),
        F(R"===(</tr>)==="),
        F(R"===(<tr>)==="),
        F(R"===(<td class="align-middle" id="n2"></td>)==="),
        F(R"===(<td class="align-middle"><div id="s2"></div></td>)==="),
        F(R"===(<td class="align-middle"><form method="post"><input name="power2" type="hidden" value="1" id="i2"><button type="submit" id="b2"></button></form></td>)==="),
        F(R"===(<td class="align-middle"><form method="post"><input name="power2" type="hidden" value="2"><button type="submit" class="btn btn-block btn-dark">Cycle</button></form></td>)==="),
        F(R"===(</tr>)==="),
        F(R"===(<tr>)==="),
        F(R"===(<td class="align-middle" id="n3"></td>)==="),
        F(R"===(<td class="align-middle"><div id="s3"></div></td>)==="),
        F(R"===(<td class="align-middle"><form method="post"><input name="power3" type="hidden" value="1" id="i3"><button type="submit" id="b3"></button></form></td>)==="),
        F(R"===(<td class="align-middle"><form method="post"><input name="power3" type="hidden" value="2"><button type="submit" class="btn btn-block btn-dark">Cycle</button></form></td>)==="),
        F(R"===(</tr>)==="),
        F(R"===(</tbody>)==="),
        F(R"===(</table>)==="),
        F(R"===(</div>)==="),
        F(R"===(<div class="row">)==="),
        F(R"===(<canvas id="flts"></canvas>)==="),
        F(R"===(</div>)==="),
        F(R"===(</div>)==="),
        F(R"===(</div>)==="),
        F(R"===(<div class="col-6">)==="),
        F(R"===(<h4 class="text-center">Battery Info</h4>)==="),
        F(R"===(<div class="col-11">)==="),
        F(R"===(<div class="row">)==="),
        F(R"===(<table class="table table-sm table-borderless">)==="),
        F(R"===(<thead>)==="),
        F(R"===(<tr>)==="),
        F(R"===(<th scope="col">Min Voltage</th>)==="),
        F(R"===(<th scope="col">Max Voltage</th>)==="),
        F(R"===(<th scope="col">Max Charge</th>)==="),
        F(R"===(<th scope="col">Max Discharge</th>)==="),
        F(R"===(<th scope="col">Max Capacity</th>)==="),
        F(R"===(<th scope="col" colspan="2">Current Temperature</th>)==="),
        F(R"===(</tr>)==="),
        F(R"===(</thead>)==="),
        F(R"===(<tbody>)==="),
        F(R"===(<tr>)==="),
        F(R"===(<td id="mv"></td>)==="),
        F(R"===(<td id="xv"></td>)==="),
        F(R"===(<td id="xc"></td>)==="),
        F(R"===(<td id="xd"></td>)==="),
        F(R"===(<td id="xp"></td>)==="),
        F(R"===(<td id="t1"></td>)==="),
        F(R"===(<td id="t2"></td>)==="),
        F(R"===(</tr>)==="),
        F(R"===(</tbody>)==="),
        F(R"===(</table>)==="),
        F(R"===(</div>)==="),
        F(R"===(<div class="row">)==="),
        F(R"===(<canvas id="tBat"></canvas>)==="),
        F(R"===(</div>)==="),
        F(R"===(<div class="row">)==="),
        F(R"===(<canvas id="celV"></canvas>)==="),
        F(R"===(</div>)==="),
        F(R"===(</div>)==="),
        F(R"===(</div>)==="),
        F(R"===(</div>)==="),
        F(R"===(<div class="row">)==="),
        F(R"===(<canvas id="temp"></canvas>)==="),
        F(R"===(</div>)==="),
        F(R"===(<script>)==="),
        F(R"===(let cT = document.getElementById('temp').getContext('2d');)==="),
        F(R"===(let tLs = [];)==="),
        F(R"===(let pD = [];)==="),
        F(R"===(let tD = [];)==="),
        F(R"===(let hD = [];)==="),
        F(R"===(let tvl = [];)==="),
        F(R"===(let rSocL = [];)==="),
        F(R"===(let rSoc = [];)==="),
        F(R"===(let cB = document.getElementById('tBat').getContext('2d');)==="),
        F(R"===(let cVL = [];)==="),
        F(R"===(let cVs = [];)==="),
        F(R"===(let cV = document.getElementById('celV').getContext('2d');)==="),
        F(R"===(let fL = [];)==="),
        F(R"===(let fCs = [];)==="),
        F(R"===(let cF = document.getElementById('flts').getContext('2d');)==="),
        F(R"===(window.fetch('switches.json'))==="),
        F(R"===(.then(response => response.json()))==="),
        F(R"===(.then(data => {data["switches"].forEach((i, index) => {)==="),
        F(R"===(document.getElementById('n'.concat(index)).innerText = i["name"];)==="),
        F(R"===(document.getElementById('s'.concat(index)).className = i["state"] ? "alert-sm alert-success text-center" : "alert-sm alert-danger text-center";)==="),
        F(R"===(document.getElementById('s'.concat(index)).innerText = i["state"] ? "On" : "Off";)==="),
        F(R"===(document.getElementById('i'.concat(index)).value = i["state"] ? "0" : "1";)==="),
        F(R"===(document.getElementById('b'.concat(index)).className = i["state"] ? "btn btn-block btn-danger" : "btn btn-block btn-success";)==="),
        F(R"===(document.getElementById('b'.concat(index)).innerText = i["state"] ? "Off" : "On";})}))==="),
        F(R"===(.then(() => {return fetch('battery.json')}))==="),
        F(R"===(.then(response => response.json()))==="),
        F(R"===(.then(data => {data["cellVoltages"].forEach((i) => {)==="),
        F(R"===(cVL.push(i["cell"].concat(i["balancing"] ? ' - bal' : ''));)==="),
        F(R"===(cVs.push(i["cellVoltage"]);)==="),
        F(R"===(});)==="),
        F(R"===(data["faults"].forEach((i) => {)==="),
        F(R"===(fL.push(i["fault"]);)==="),
        F(R"===(fCs.push(i["count"]);)==="),
        F(R"===(});)==="),
        F(R"===(tvl.push(data["totalVoltage"]);)==="),
        F(R"===(rSocL.push('Charging: '.concat(data["charge"]).concat(' - Discharging: ').concat(data["discharge"]));)==="),
        F(R"===(rSoc.push(data["remainingSOC"]);)==="),
        F(R"===(document.getElementById("mv").innerText = data["minVoltage"];)==="),
        F(R"===(document.getElementById("xv").innerText = data["maxVoltage"];)==="),
        F(R"===(document.getElementById("xc").innerText = data["maxCharge"];)==="),
        F(R"===(document.getElementById("xd").innerText = data["maxDischarge"];)==="),
        F(R"===(document.getElementById("xp").innerText = data["maxPower"];)==="),
        F(R"===(document.getElementById("t1").innerText = data["temp1"];)==="),
        F(R"===(document.getElementById("t2").innerText = data["temp2"];)==="),
        F(R"===(document.getElementById('tBat').height = 81;}))==="),
        F(R"===(.then(() => {new Chart(cB, {)==="),
        F(R"===(type: 'horizontalBar',)==="),
        F(R"===(data: {)==="),
        F(R"===(labels: tvl,)==="),
        F(R"===(datasets: [{label: rSocL, backgroundColor: 'rgba(0, 0, 255, 0.5)', borderColor: 'rgba(0, 0, 255, 1)', data: rSoc}]},)==="),
        F(R"===(options: {scales: {xAxes: [{ticks: {beginAtZero: true, suggestedMax: 100}}]}}});}))==="),
        F(R"===(.then(() => {new Chart(cV, {)==="),
        F(R"===(type: 'bar',)==="),
        F(R"===(data: {)==="),
        F(R"===(labels: cVL,)==="),
        F(R"===(datasets: [{label: 'Cell Voltage', backgroundColor: 'rgba(0, 255, 0, 0.5)', borderColor: 'rgba(0, 255, 0, 1)', data: cVs}]},)==="),
        F(R"===(options: {scales: {yAxes: [{scaleLabel: {display:true, labelString:'Volts'}, ticks: {beginAtZero: true}}]}}});}))==="),
        F(R"===(.then()==="),
        F(R"===(() => {new Chart(cF, {)==="),
        F(R"===(type: 'horizontalBar',)==="),
        F(R"===(data: {)==="),
        F(R"===(labels: fL,)==="),
        F(R"===(datasets: [{label: 'Faults', backgroundColor: 'rgba(255, 0, 0, 0.5)', borderColor: 'rgba(255, 0, 0, 1)', data: fCs}]},)==="),
        F(R"===(});}))==="),
        F(R"===(.then(() => { return fetch('sensors.json')}))==="),
        F(R"===(.then(response => response.json()))==="),
        F(R"===(.then(data => data["values"].forEach((i) => {)==="),
        F(R"===(tLs.push(i["time"]);)==="),
        F(R"===(pD.push(i["pressure"]);)==="),
        F(R"===(tD.push(i["temp"]);)==="),
        F(R"===(hD.push(i["humidity"]);)==="),
        F(R"===(})))==="),
        F(R"===(.then(() => {new Chart(cT, {)==="),
        F(R"===(type: 'line',)==="),
        F(R"===(data: {)==="),
        F(R"===(labels: tLs,)==="),
        F(R"===(datasets: [{label: 'Temperature', fill: false, backgroundColor: 'rgba(255, 0, 0, 0.5)', borderColor: 'rgba(255, 0, 0, 0.5)', yAxisID: '1', data: tD},)==="),
        F(R"===({label: 'Humidity', fill: false, backgroundColor: 'rgba(0, 0, 255, 0.5)', borderColor: 'rgba(0, 0, 255, 0.5)', yAxisID: '1', data: hD},)==="),
        F(R"===({label: 'Barometric Pressure', fill: false, backgroundColor: 'rgba(0, 255, 0, 0.5)', borderColor: 'rgba(0, 255, 0, 0.5)', yAxisID: '2', data: pD}]},)==="),
        F(R"===(options: {)==="),
        F(R"===(scales: {)==="),
        F(R"===(yAxes: [{type: 'linear', position: 'left', id: '1'},)==="),
        F(R"===({type: 'linear', position: 'right', id: '2'}])==="),
        F(R"===(}}});}))==="),
        F(R"===(.catch((error) => {)==="),
        F(R"===(console.log('Error', error);)==="),
        F(R"===(});)==="),
        F(R"===(</script>)==="),
        F(R"===(</div>)==="),
        F(R"===(</body>)==="),
        F(R"===(</html>)===")
};
#endif //POWER_CONTROLLER_EVERY2_INDEXPAGE_H
